// =============================================================
// ALIGN v2 — Reactive State Store
// Central state with subscriber pattern for efficient re-renders
// =============================================================

const LS_PREFIX = 'align_v2_';

// ─── Default State ───

function getEmptyDayLog() {
  return {
    steps: 0,
    water: 0,
    sleep: 0,
    weight: 0,
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    meals: [],
    workouts: [],
    habitsCompleted: [],
    aiReview: null,
    pagesRead: 0,
    activeBurn: 0,
    chatHistory: [],
    notes: '',
    sleepTime: null,
    wakeTime: null,
  };
}

const DEFAULT_STATE = {
  // Auth
  user: null,

  // User profile
  profile: null,

  // Navigation
  activeView: 'dashboard',

  // Date
  dateStr: new Date().toISOString().split('T')[0],

  // Time period (morning | midday | evening | night)
  timePeriod: 'morning',

  // Daily logs indexed by YYYY-MM-DD
  logs: {},

  // Workout split definitions
  workoutSplits: {
    'Push Day': [
      { name: 'Bench Press', sets: 4, reps: 10, weight: 60 },
      { name: 'Incline DB Press', sets: 3, reps: 12, weight: 20 },
      { name: 'Tricep Pushdowns', sets: 4, reps: 15, weight: 25 },
    ],
    'Pull Day': [
      { name: 'Lat Pulldown', sets: 4, reps: 10, weight: 50 },
      { name: 'Barbell Row', sets: 3, reps: 8, weight: 40 },
      { name: 'Bicep Curls', sets: 3, reps: 12, weight: 12 },
    ],
    'Legs Day': [
      { name: 'Squats', sets: 4, reps: 8, weight: 80 },
      { name: 'Romanian Deadlift', sets: 3, reps: 10, weight: 60 },
      { name: 'Calf Raises', sets: 4, reps: 15, weight: 40 },
    ],
  },

  // Custom recipes
  recipes: [],

  // Habits list
  habits: [
    { id: 'h1', title: 'Read 15 Pages', category: 'Mind', icon: 'book' },
    { id: 'h2', title: '10k Steps Walked', category: 'Fitness', icon: 'footprints' },
    { id: 'h3', title: 'Hydrated (8+ Cups)', category: 'Health', icon: 'water' },
    { id: 'h4', title: 'No processed food', category: 'Nutrition', icon: 'utensils' },
  ],

  // Books & movies
  books: [],
  movies: [],

  // Personal Records
  personalRecords: {},

  // Insight queue (generated by pattern engine)
  insightQueue: [],

  // User model (Align Brain)
  userModel: {
    patterns: {},
    milestones: [],
    struggles: [],
  },
};

// ─── State Container ───

let _state = {};
const _subscribers = {};     // key → Set<callback>
const _globalSubs = new Set(); // called on any change

/**
 * Initialize state from localStorage + defaults.
 */
export function initState() {
  _state = { ...DEFAULT_STATE };

  // Restore persisted keys
  const persistedKeys = [
    'profile', 'logs', 'workoutSplits', 'recipes',
    'habits', 'books', 'movies', 'userModel', 'insightQueue',
    'personalRecords',
  ];

  for (const key of persistedKeys) {
    const stored = localStorage.getItem(LS_PREFIX + key);
    if (stored) {
      try {
        _state[key] = JSON.parse(stored);
      } catch (e) {
        console.warn(`Failed to parse stored ${key}:`, e);
      }
    }
  }

  // Detect time period
  _state.timePeriod = detectTimePeriod();

  // Check for plaintext keys in profile, migrate to sessionStorage, and scrub from localStorage
  if (_state.profile) {
    let updated = false;
    if (_state.profile.geminiApiKey) {
      setGeminiKey(_state.profile.geminiApiKey);
      delete _state.profile.geminiApiKey;
      _state.profile.hasGeminiKey = true;
      updated = true;
    }
    if (_state.profile.omdbApiKey) {
      setOmdbKey(_state.profile.omdbApiKey);
      delete _state.profile.omdbApiKey;
      _state.profile.hasOmdbKey = true;
      updated = true;
    }
    if (updated) {
      localStorage.setItem(LS_PREFIX + 'profile', JSON.stringify(_state.profile));
    }
  }

  // 1c. Bidirectionally sync habits and logs immediately on init
  syncAllHabitsAndLogs();
}

let _isSyncing = false;
export function syncAllHabitsAndLogs() {
  if (_isSyncing) return;
  _isSyncing = true;
  try {
    const habits = _state.habits || [];
    const logs = _state.logs || {};
    let logsUpdated = false;
    let habitsUpdated = false;

    // 1. Ensure dates in completions are in logs
    const newHabits = habits.map(h => {
      const completionsSet = new Set(h.completions || []);
      const originalSize = completionsSet.size;

      completionsSet.forEach(dateStr => {
        if (!logs[dateStr]) {
          logs[dateStr] = getEmptyDayLog();
          logsUpdated = true;
        }
        if (!logs[dateStr].habitsCompleted) {
          logs[dateStr].habitsCompleted = [];
          logsUpdated = true;
        }
        if (!logs[dateStr].habitsCompleted.includes(h.id)) {
          logs[dateStr].habitsCompleted.push(h.id);
          logsUpdated = true;
        }
      });

      // 2. Ensure dates in logs are in completions
      Object.keys(logs).forEach(dateStr => {
        const day = logs[dateStr];
        if (day && day.habitsCompleted && day.habitsCompleted.includes(h.id)) {
          if (!completionsSet.has(dateStr)) {
            completionsSet.add(dateStr);
            habitsUpdated = true;
          }
        }
      });

      if (completionsSet.size !== originalSize) {
        habitsUpdated = true;
      }
      return { ...h, completions: Array.from(completionsSet) };
    });

    // 3. Prune orphaned habit IDs from logs
    const activeHabitIds = new Set(habits.map(h => h.id));
    Object.keys(logs).forEach(dateStr => {
      const day = logs[dateStr];
      if (day && day.habitsCompleted) {
        const filtered = day.habitsCompleted.filter(id => activeHabitIds.has(id));
        if (filtered.length !== day.habitsCompleted.length) {
          day.habitsCompleted = filtered;
          logsUpdated = true;
        }
      }
    });

    if (logsUpdated) {
      setState('logs', { ...logs });
    }
    if (habitsUpdated) {
      setState('habits', newHabits);
    }
  } finally {
    _isSyncing = false;
  }
}

/**
 * Get a state value.
 */
export function getState(key) {
  if (key === undefined) return { ..._state };
  return _state[key];
}

/**
 * Set a state value and notify subscribers.
 */
export function setState(key, value) {
  const prev = _state[key];
  _state[key] = value;

  // Persist if it's a persistable key
  const persistedKeys = [
    'profile', 'logs', 'workoutSplits', 'recipes',
    'habits', 'books', 'movies', 'userModel', 'insightQueue',
    'personalRecords',
  ];
  if (persistedKeys.includes(key)) {
    try {
      localStorage.setItem(LS_PREFIX + key, JSON.stringify(value));
    } catch (e) {
      console.warn(`Failed to persist ${key}:`, e);
    }
  }

  // Notify key-specific subscribers
  if (_subscribers[key]) {
    for (const cb of _subscribers[key]) {
      try { cb(value, prev, key); } catch (e) { console.error('Subscriber error:', e); }
    }
  }

  // Notify global subscribers
  for (const cb of _globalSubs) {
    try { cb(key, value, prev); } catch (e) { console.error('Global subscriber error:', e); }
  }

  // Auto-sync logs/habits when habits or logs change
  if (key === 'habits' || key === 'logs') {
    syncAllHabitsAndLogs();
  }
}

/**
 * Subscribe to changes on a specific key.
 * Returns an unsubscribe function.
 */
export function subscribe(key, callback) {
  if (!_subscribers[key]) _subscribers[key] = new Set();
  _subscribers[key].add(callback);
  return () => _subscribers[key].delete(callback);
}

/**
 * Subscribe to any state change.
 */
export function subscribeAll(callback) {
  _globalSubs.add(callback);
  return () => _globalSubs.delete(callback);
}

// ─── Day Log Helpers ───

/**
 * Get today's log (creates if needed).
 */
export function getDayLog(dateStr) {
  const d = dateStr || _state.dateStr;
  const logs = _state.logs;

  if (!logs[d]) {
    logs[d] = getEmptyDayLog();
    setState('logs', { ...logs });
  }

  // Normalize — fill in missing fields
  const day = logs[d];
  const defaults = getEmptyDayLog();
  for (const key in defaults) {
    if (day[key] === undefined || day[key] === null) {
      day[key] = defaults[key];
    }
  }

  return day;
}

/**
 * Update a field in today's log and persist.
 */
export function updateDayLog(dateStr, updates) {
  const d = dateStr || _state.dateStr;
  const day = getDayLog(d);

  Object.assign(day, updates);

  // Auto-sync habits based on metric goals
  syncAutoHabits(day);

  const logs = { ..._state.logs, [d]: day };
  setState('logs', logs);

  // Sync completions
  syncAllHabitsAndLogs();
}

/**
 * Sync habits that auto-complete based on metrics.
 */
function syncAutoHabits(day) {
  if (!day.habitsCompleted) day.habitsCompleted = [];
  const profile = _state.profile || {};

  const stepGoal = profile.targetSteps || 10000;
  const waterGoal = profile.targetWater || 8;

  // Reading habit (h1)
  const hasReadHabit = day.habitsCompleted.includes('h1');
  const targetPages = 15;
  if (day.pagesRead >= targetPages && !hasReadHabit) {
    day.habitsCompleted.push('h1');
  } else if (day.pagesRead < targetPages && hasReadHabit) {
    day.habitsCompleted = day.habitsCompleted.filter(id => id !== 'h1');
  }

  // Steps habit (h2)
  const hasStepHabit = day.habitsCompleted.includes('h2');
  if (day.steps >= stepGoal && !hasStepHabit) {
    day.habitsCompleted.push('h2');
  } else if (day.steps < stepGoal && hasStepHabit) {
    day.habitsCompleted = day.habitsCompleted.filter(id => id !== 'h2');
  }

  // Water habit (h3)
  const hasWaterHabit = day.habitsCompleted.includes('h3');
  if (day.water >= waterGoal && !hasWaterHabit) {
    day.habitsCompleted.push('h3');
  } else if (day.water < waterGoal && hasWaterHabit) {
    day.habitsCompleted = day.habitsCompleted.filter(id => id !== 'h3');
  }
}

// ─── Computed Values ───

/**
 * Active calorie burn estimate.
 */
export function getActiveBurn(day) {
  if (day && typeof day.activeBurn === 'number' && day.activeBurn > 0) {
    return Math.round(day.activeBurn);
  }
  let burn = 0;
  if (day?.steps > 0) burn += day.steps * 0.04;
  if (day?.workouts?.length > 0) {
    const totalSets = day.workouts.reduce((acc, ex) => acc + (parseInt(ex.sets) || 0), 0);
    burn += 150 + (totalSets * 20);
  }
  return Math.round(burn);
}

/**
 * Compute daily score (0-100).
 */
export function computeDailyScore(day) {
  const profile = _state.profile || {};
  const habits = _state.habits || [];

  const stepGoal = profile.targetSteps || 10000;
  const calGoal = profile.targetCalories || 2000;
  const sleepGoal = profile.targetSleep || 8;
  const waterGoal = profile.targetWater || 8;

  const stepScore = Math.min(100, ((day.steps || 0) / stepGoal) * 100);
  const sleepScore = Math.min(100, ((day.sleep || 0) / sleepGoal) * 100);
  const waterScore = Math.min(100, ((day.water || 0) / waterGoal) * 100);

  const netCals = Math.max(0, (day.calories || 0) - getActiveBurn(day));
  const calScore = calGoal > 0 ? Math.min(100, (netCals / calGoal) * 100) : 50;

  const habitCount = habits.length || 1;
  const completedCount = (day.habitsCompleted || []).length;
  const habitScore = Math.min(100, (completedCount / habitCount) * 100);

  return Math.round((stepScore + sleepScore + waterScore + calScore + habitScore) / 5);
}

/**
 * Get 7-day average trends.
 */
export function getWeeklyTrends(baseDateStr) {
  const baseDate = new Date(baseDateStr || _state.dateStr);
  let stepsSum = 0, stepsN = 0;
  let sleepSum = 0, sleepN = 0;
  let calSum = 0, calN = 0;
  const weights = [];

  for (let i = 0; i < 7; i++) {
    const d = new Date(baseDate);
    d.setDate(baseDate.getDate() - i);
    const key = d.toISOString().split('T')[0];
    const day = _state.logs[key];
    if (!day) continue;

    if (day.steps > 0) { stepsSum += day.steps; stepsN++; }
    if (day.sleep > 0) { sleepSum += day.sleep; sleepN++; }
    if (day.calories > 0) { calSum += day.calories; calN++; }
    if (day.weight > 0) weights.push({ date: key, weight: day.weight });
  }

  weights.sort((a, b) => a.date.localeCompare(b.date));
  let weightChange = 0;
  if (weights.length >= 2) {
    weightChange = weights[weights.length - 1].weight - weights[0].weight;
  }

  return {
    avgSteps: stepsN > 0 ? Math.round(stepsSum / stepsN) : 0,
    avgSleep: sleepN > 0 ? parseFloat((sleepSum / sleepN).toFixed(1)) : 0,
    avgCalories: calN > 0 ? Math.round(calSum / calN) : 0,
    weightChange: parseFloat(weightChange.toFixed(1)),
    latestWeight: weights.length > 0 ? weights[weights.length - 1].weight : null,
  };
}

// ─── Time Period Detection ───

export function detectTimePeriod() {
  const hour = new Date().getHours();
  if (hour >= 5 && hour < 10) return 'morning';
  if (hour >= 10 && hour < 16) return 'midday';
  if (hour >= 16 && hour < 21) return 'evening';
  return 'night';
}

export function getGreeting() {
  const name = _state.profile?.name || '';
  const firstName = name.split(' ')[0] || '';
  const period = _state.timePeriod;

  const greetings = {
    morning: firstName ? `Good morning, ${firstName}` : 'Good morning',
    midday: firstName ? `Hey ${firstName}` : 'Good afternoon',
    evening: firstName ? `Evening, ${firstName}` : 'Good evening',
    night: firstName ? `Wind down, ${firstName}` : 'Night mode',
  };

  return greetings[period] || greetings.morning;
}

export { getEmptyDayLog };

// ─── XOR Obfuscation System ───
const SESSION_SALT = Math.random().toString(36).substring(2) + Date.now().toString();

function xorEncrypt(text) {
  if (!text) return '';
  let result = '';
  for (let i = 0; i < text.length; i++) {
    const charCode = text.charCodeAt(i) ^ SESSION_SALT.charCodeAt(i % SESSION_SALT.length);
    result += String.fromCharCode(charCode);
  }
  return btoa(result);
}

function xorDecrypt(encrypted) {
  if (!encrypted) return '';
  try {
    const text = atob(encrypted);
    let result = '';
    for (let i = 0; i < text.length; i++) {
      const charCode = text.charCodeAt(i) ^ SESSION_SALT.charCodeAt(i % SESSION_SALT.length);
      result += String.fromCharCode(charCode);
    }
    return result;
  } catch (e) {
    return '';
  }
}

export function getGeminiKey() {
  const encrypted = sessionStorage.getItem('align_gemini_key');
  return xorDecrypt(encrypted) || null;
}

export function setGeminiKey(key) {
  if (key) {
    sessionStorage.setItem('align_gemini_key', xorEncrypt(key));
  } else {
    sessionStorage.removeItem('align_gemini_key');
  }
}

export function getOmdbKey() {
  const encrypted = sessionStorage.getItem('align_omdb_key');
  return xorDecrypt(encrypted) || null;
}

export function setOmdbKey(key) {
  if (key) {
    sessionStorage.setItem('align_omdb_key', xorEncrypt(key));
  } else {
    sessionStorage.removeItem('align_omdb_key');
  }
}

